language: r
before_install:
  - sudo mkdir -p /usr/lib/R/library
  - echo 'R_LIBS=/usr/lib/R/library:/usr/lib/R/site-library/' > ~/.Renviron
  - sudo chmod 2777 /usr/lib/R/library
install:
  - R -e "0" --args --bootstrap-packrat
cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true
script: 
  - nohup R --slave --no-restore -e 'shiny::runApp(port = 6012)' &
  - R -f test-basic.R
addons:
  sauce_connect:
    username: $SAUCE_USERNAME
    access_key: $SAUCE_SECRET_KEY
